repos:
  # linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.5
    hooks:
      - id: ruff  # Linter
        args: [--fix]  # Ensure fixes are applied
      - id: ruff-format  # Formatter

  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.15.0  # Use the sha / tag you want to point at
      hooks:
      -   id: mypy